<?php
    //english lang

    //nav
    $lang['lang-eng'] = 'English';
    $lang['lang-ger'] = 'German';

    //index
    $lang['index-title'] = 'Vestamatic ENG';
    $lang['nav-about'] = 'ABOUT';
    $lang['nav-manuals'] = 'MANUALS';
    $lang['nav-contact'] = 'CONTACT';

    //header
    $lang['head-small'] = 'WE ARE VESTAMATIC';
    $lang['head-large'] = 'Vestamatic CRE is the global solution provider in dynamic facades.';

    //about
    $lang['about-head'] = 'ABOUT US';
    $lang['about-1'] = 'Vestamatic + CRE GmbH is a privately-owned company with its headquarters in Mönchengladbach, Germany. Vestamatic + CRE is a leading manufacturer of automation solutions to the shading market for over 40 years.';
    $lang['about-2'] = 'Vestamatic + CRE meets the needs of today’s buildings and future developments with in-house electronic design, manufacture and firmware development, scalable engineering solutions and expert support. With our focus on specification, commissioning and maintenance of contract and hospitality shading automation, we design, create and deliver one-stop-shop solutions with our partners. ';
    $lang['about-3'] = 'We run technology commonly used in buildings like KNX, BACNET, TCP/IP to connect and integrate shading into these. We run unique features in motors, wiring, automation, and service. Some of the biggest and most sophisticated buildings in the world are currently equipped with technology provided by Vestamatic + CRE.';
    $lang['about-4'] = 'Below you find technical product data for download and a request link for more information on these. Should you need a full scale project solution, please contact us. Please also visit our solution websites www.vestamaticcre.com and www.vcp-network.com.';
    $lang['about-5'] = 'Vestamatic + CRE only delivers B2B and can recommend distribution partners if needed.';

    //footer
    $lang['imprint'] = 'IMPRINT';

    ////////////////////////////////////////////////////////
    // Imprint
    $lang['responsible'] = 'Responsible for this website is:';
    $lang['inf_duties'] = 'Information duties according §18 Abs. 2 Elektro- und Elektronikgerätegesetz';
    $lang['director'] = 'Managing Director';

    ////////////////////////////////////////////////////////
    // AGB
    $lang['agb_head'] = 'Terms and Conditions – Deliveries and Services (AGB) 2021';
    $lang['agb_1_head'] = 'I. Validity of conditions';
    $lang['agb_1'] = 'All supplies, services and offers by the vendor shall be based exclusively on these general terms and conditions. These shall therefore also apply to all future business relations, even in the absence of any specific additional agreements. These conditions shall be considered as having been accepted not later than the date on which the goods or services are accepted. Buyer’s terms and conditions shall not apply. Any counter-confirmation by the purchaser, making reference to his terms and conditions are hereby precluded. ';
    $lang['agb_2_head'] = 'II. Offer, conclusion of contract, technical properties and documentation';
    $lang['agb_2_1'] = 'Vendor’s offers are subject to confirmation. Legally binding are only the vendor’s order confirmations.';
    $lang['agb_2_2'] = 'Any data in brochures, drawings, illustrations, measurements, specifically assembly dimensions and weights are firm only if explicitly agreed to in writing or text form.';
    $lang['agb_2_3'] = 'The technical properties of the supply items are described in the product information of the vendor and are in accordance with the technical standards referred to therein. Any product information provided by the vendor to the purchaser shall be free of charge. Any features of the supply items in addition to the abovementioned product properties shall be deemed as agreed only, if separately recorded by the vendor.';
    $lang['agb_2_4'] = 'The vendor shall not be liable for the compatibility of the supply items with control units or equipments, data processing systems or building management systems, unless specifically offered or approved by the vendor. Clearance certificates must be issued in writing or text form.';
    $lang['agb_2_5'] = 'In the case of custom manufacture, the vendor shall be entitled to supply up to 10 % more or 10 % less than the agreed quantities.';
    $lang['agb_2_6'] = 'The vendors texts and pictures are usable only after written acceptance of the vendor. They remain solely owned by the vendor.';
    $lang['agb_3_head'] = 'III. Delivery periods, delay';
    $lang['agb_3_1'] = 'Compliance with the agreed delivery dates shall be subject to the purchaser’s compliance with the agreed payment terms, including the timely delivery of all documentation, plans, necessary permits and approvals by the purchaser. If these conditions are not complied within due time, the delivery dates are appropriately extended; however, this shall not be applicable, if the vendor is responsible for the delay.';
    $lang['agb_3_2'] = 'The delivery date is extended appropriately, if the non-compliance with the delivery date is due to force majeure, such as mobilization, war, riots or similar events, e.g. strike or lockout. The vendor shall also not be responsible for delays due to the above-mentioned circumstances if they occur during an existing delay.';
    $lang['agb_3_3'] = 'Part shipments are permissible.';
    $lang['agb_3_4'] = 'The vendor shall be deemed to be in default, if the delivery is due and after a reminder in written or text form has been issued, except when a specific delivery date was agreed. In all cases of late delivery, the purchaser shall not be entitled to any compensation; this shall also be applicable, where an extension that was granted by the purchaser has been exceeded. This shall not apply, where mandatory liability exists in cases of willful misconduct or gross negligence as a result of personal injuries, health detriment, or death. This is not related to a change in the burden of proof to the detriment of the purchaser. The purchaser’s statutory right to withdraw from the agreement shall remain unaffected.';
    $lang['agb_3_5'] = 'The purchaser is permitted to withdraw from the agreement within the limits imposed by law only if the vendor is responsible for the delay.';
    $lang['agb_3_6'] = 'If so requested by the vendor, the purchaser is obligated to declare within a reasonable period whether he intends to withdraw from the agreements or whether he demands compensatory damage in place of performance, or whether he abides by the agreement.';
    $lang['agb_4_head'] = 'IV. Scope of supply and services';
    $lang['agb_4_1'] = 'The scope of supply shall be specified in the vendor’s order confirmation in written or text form.';
    $lang['agb_4_2'] = 'The right to make technical modifications due to technical improvements and/or as a result of legislative requirements which occur during the delivery period shall be reserved, provided that no major change of the supply item results and that such changes can be reasonably accepted by the purchaser.';
    $lang['agb_4_3'] = 'Oral consulting services are binding only when confirmed in writing through the vendor.';
    $lang['agb_4_4'] = 'The vendor is not obliged to supply long term supplier agreements nor declaration of origin unless legally required.';
    $lang['agb_5_head'] = 'V. Cancellation costs';
    $lang['agb_5'] = 'If the purchaser cancels the order without justification, the vendor may demand 10% of the sales price as compensation for order processing costs and possible loss of earnings, without prejudice to the option of claiming higher than actual damage. The purchaser shall retain the right to provide documentation to the extent that the damage is lower or that no damage has occurred.';
    $lang['agb_6_head'] = 'VI. Packaging and shipping';
    $lang['agb_6'] = ' Shipment shall be ex the vendor’s works, otherwise unless specified in the order confirmation. If the purchaser requests shipment by the vendor, the transport shall always be at the purchaser’s risk. In this case, the vendor invoices the usual freight and packaging costs. The choice of shipping method shall be at the vendor’s discretion. Transport insurance is available on request and at the purchaser’s expense. ';
    $lang['agb_7_head'] = 'VII. Transfer of risk / Approval';
    $lang['agb_7_1'] = 'Risk shall pass to the purchaser even in case of carriage paid delivery with the handing over to the carrier or collector; transport insurance is available on request and at the purchaser’s expense. This also includes vendor implementations of items installed by the purchaser.';
    $lang['agb_7_2'] = 'The purchaser approves developments and services in form of products, prototypes, customized products or services in a written The place of performance and jurisdiction is Mönchen-gladbach, if not agreed differently. Should the purchaser not release the development or services with approval within a reasonable timeframe, the development is approved 6 weeks after the supply of the products, prototypes or customized products. The approval releases the final account and the unconditional use of the development or services.';
    $lang['agb_7_3'] = 'A multi-phased development or service can be invoiced as part approval when agreed. § VII.2 is applied for these approvals as well. multi-phased development or service can be invoiced as part approval when agreed. § VII.2 is applied for these approvals as well.';
    $lang['agb_8_head'] = 'VIII. Liability for material defects (warranty)';
    $lang['agb_8_0'] = 'The vendor or shall be liable for material defects as follows: ';
    $lang['agb_8_1'] = 'Parts or services which exhibit material defects within the period of limitation shall, at the option of the vendor be repaired, newly supplied or newly created, provided that the cause of the material defects already existed at the time of the passing of risk (supplementary performance).';
    $lang['agb_8_2'] = 'The vendor must always first be given an extension to fulfill his obligation within a reasonable time. Should this be refused, he shall be exempted with respect to any liability for material defects. If the vendor fails to fulfill his obligation within the extension period, the purchaser may withdraw from the contract or reduce the compensatory damage without prejudice to any potential claims for damages.';
    $lang['agb_8_3'] = 'Claims for compensation of material defects are subject to a limitation period of 12 months. The term starts at the time of passing the risk. The above provisions shall not be appli­cable, if the law obligatorily provides longer terms pursuant to §§ 438, paragraph 1, No. 2 (construction projects), 479, paragraph 1 (right of recourse) and 634a (structural defects) of the BGB [BGB = German Civil Code].';
    $lang['agb_8_4'] = 'The purchaser shall notify the vendor immediately with respect to any material defects. Any visible damage to the outside packaging must be reported to the freight forwarder immediately; shortages shall be reported within four business days.';
    $lang['agb_8_5'] = 'With respect to the notification of defects, the purchaser may only withhold payments if a defect notification has been asserted beyond legitimate doubt, or if the defect notification has been indisputably determined by a legal decision. Deliveries with minor defects cannot be rejected by the purchaser.';
    $lang['agb_8_6'] = 'After the risk has passed, warranty claims shall not be recognized in the event of insignificant deviations from the agreed quality, minor reduction in usability, normal wear and tear or damage as a result of incorrect or negligent handling, excessive loading, use of unsuitable equipment, inadequate construction work or as a result of any special external influences not provided for in the agreement, including any non-reproducible software defects claimed. Warranty claims shall not be recognized in the event of improper modifications or installation by the purchaser or third parties and through any consequences resulting therefrom.';
    $lang['agb_8_7'] = 'Claims by the purchaser because of necessary expenses for the purpose of remediating the defects in performance, specifically costs in respect of transport, infrastructure, labor and materials, shall be excluded if the additional costs were caused because the supply item was transferred to a different location from the place of delivery, unless the transfer has been agreed upon between the parties.';
    $lang['agb_8_8'] = 'The purchaser shall have recourse claims against the vendor only in so far that the purchaser has not agreed any additional conditions beyond the statutory warranty claims with his customer.';
    $lang['agb_8_9'] = 'In all other respects, compensatory damages shall be subject to Section XI (other compensatory claims). Any additional or different claims other than the claims agreed to above by the purchaser against the vendor or persons employed by him in the performance of his obligation as a result of material defects shall be excluded.';
    $lang['agb_8_10'] = 'The purchaser is obligated to pay to the vendor the costs and expenses arising where the purchaser demands the remediation of a defect during the defects liability period and it however transpires that no material defect exists.';
    $lang['agb_9_head'] = 'IX. Retention of title / Intellectual Property';
    $lang['agb_9_1'] = 'The supply items (goods subject to the retention of title) shall remain the property of the vendor until such time that any claims by him against the purchaser in terms of the business relationship have been satisfied. If the value of all security interests to which the vendor is entitled exceeds the amount of all secured claims by more than 20%, the vendor shall release an appropriate percentage of the security interests if so requested by the purchaser.';
    $lang['agb_9_2'] = 'During the existence of a retention of title, the purchaser shall not be permitted to pledge or transfer ownership by way of security and may permit resale by resellers only in the normal course of business and on condition that the reseller is paid by his customer or reserves the right that ownership will be transferred to the customer only after he has fulfilled his payment obligations.';
    $lang['agb_9_3'] = 'In the event of an attachment of property, confiscation, or other decrees or through the intervention of third parties, the purchaser must notify the vendor immediately.';
    $lang['agb_9_4'] = 'If the purchaser fails to comply with his duty, specifically, the failure to pay on due date, the vendor is entitled to cancel the agreement and take back the goods, while the purchaser is obligated to surrender the goods. Taking back the goods and/or enforcing the retention of title does not require the purchaser to withdraw. These actions by the vendor or the attachment of the goods subject to the retention of title does not imply a withdrawal from the agreement, unless specifically stated by the vendor.';
    $lang['agb_9_5'] = 'With respect to the resale of the goods subject to the retention of title by the purchaser, the purchaser hereby agrees to assign all receivables which accrue to the purchaser from the resale, equal to the price (including VAT) agreed between the vendor and the purchaser; this shall occur irrespective of whether the supply items were resold prior or subsequent to any subsequent fabrication. The vendor shall be entitled to collect these receivables. However, the right of the purchaser to collect these receivables directly shall remain unaffected; the vendor, however, shall be obligated to refrain from collecting these receivables, provided that the purchaser meets his obligation to pay appropriately and is not in default in payment. However, should the purchaser be in default, the vendor may demand the purchaser to disclose all details of the assigned receivables and the debtors, provide all necessary information for the collection of receivables, hand over all relevant documentation and notify the debtors (third parties) of the assignment.';
    $lang['agb_9_6'] = 'The purchaser is granted usage rights on the developments once the results are approved and the final invoice is paid without deduction. The purchaser only receives the usage rights as defined in the separated contract. Should the vendor use existing intellectual property for the development, the purchaser is only granted a limited right of usage. The vendor remains the sole owner of the intellectual property.';
    $lang['agb_9_7'] = 'Vendor and purchaser will agree consensual on how rights of third parties affecting the development, will be included.';
    $lang['agb_10_head'] = 'X. Impossibility of performance, adaptation of contract';
    $lang['agb_10_1'] = 'If delivery is impossible, the purchaser is entitled to claim compensatory damages, unless the inability to supply is beyond the vendor’s control. Any compensatory claims by the purchaser shall however be limited to 10% of the value of the respective part of the supply that cannot be utilized because of the inability to supply. This limitation shall not apply, if liability exists due to willful misconduct, gross negligence, or physical injuries. This provision does not require amending the burden of proof to the purchaser’s disadvantage. The right of the purchaser to withdraw from the agreement remains unaffected, even in the event that an extension of the delivery period had been previously agreed with the purchaser. In the event of a temporary impossibility of performance, the provisions under paragraph III (delivery periods, delay) shall apply.';
    $lang['agb_10_2'] = 'In the event that unforeseen circumstances in terms of paragraph III, No. 2 have a material impact upon the economic consequences or on the scope of supply or if they significantly affect the vendor’s operations, this agreement shall be appropriately adapted in good faith. Should this not be tenable from a business perspective, the vendor shall have the right to withdraw from the agreement. If he intends to invoke this right, he must inform the purchaser immediately after realizing the implications of this action.';
    $lang['agb_11_head'] = 'XI. Other compensatory claims';
    $lang['agb_11_1'] = 'Compensatory claims by the purchaser, irrespective of their legal basis, particularly if due to a violation of the relationship under the law obligations and tortious acts, are excluded. This shall not apply where mandatory liability exists, e.g. pursuant to the Product Liability Act, in cases of willful misconduct or gross negligence or as a result of personal injuries, health detriment, or death, or because of the violation of significant obligations in terms of the agreement.';
    $lang['agb_11_2'] = 'However, compensatory damages for the violation of significant obligations under the agreement shall be limited to foreseeable, typical contractual damages, except for cases of willful misconduct or gross negligence, or because of warrantied characteristics.';
    $lang['agb_11_3'] = 'The foregoing arrangements shall not affect the burden of proof to the detriment of the purchaser.';
    $lang['agb_11_4'] = 'The vendor is not liable for technical and/ or commercial usability of development results. The vendor is not liable for any consequences caused by the fact that the purchaser markets products before final release of the developments.';
    $lang['agb_12_head'] = 'XII. Payment terms, set-off, EAN';
    $lang['agb_12_1'] = 'Invoices must be paid for immediately and without deductions. Discounts are applicable only, if stated in the order confirmation. Discounts may not be taken on new invoices, as long as older invoices that are due for payment are still outstanding.';
    $lang['agb_12_2'] = 'The purchaser shall be deemed to be in default with respect to payment if he has not paid within 30 days of receipt of invoice.';
    $lang['agb_12_3'] = 'The acceptance of drafts is subject to previous agreement in written or text form. The acceptance of drafts shall be subject to standard bank interest rates and fees, payable immediately in cash.';
    $lang['agb_12_4'] = 'The purchaser shall be entitled to the right of setting off on the condition that his counterclaims are determined to be legitimate and uncontested and are acknowledged by the vendor. The purchaser shall have no right of retention with respect to any contested counterclaims.';
    $lang['agb_12_5'] = 'Without the vendors written permission, the purchaser is not allowed to use the brand “Vestamatic” or any other Vestamatic product brands in any way and concerning Vestamatic products to apply for EAN-codes or any similar codes and to use those codes.';
    $lang['agb_13_head'] = 'XIII. Place of performance, jurisdiction';
    $lang['agb_13_1'] = 'The place of performance and jurisdiction is Mönchengladbach.';
    $lang['agb_13_2'] = 'German law shall apply exclusively, subject to the exclusion of the law governing the international sale of movable property, even if the purchaser’s corporate domicile is located in a foreign country.';
    $lang['agb_13_3'] = 'If a provision of this agreement shall be or become invalid, then this shall not affect the validity of the other provisions.';

?>